__parent__: config/shapenet.yaml

model:
  params:
    num_classes: null

trainer:
  params:
    mixed_precision: no

dataset:
  params:
    ds_opt:
      params:
        cates: car

sched:
  params:
    factor: 0.9
    patience: 10
